Rate limiting
nightknighto/SemiColon-backend pull request #30
Opened 2023-07-07 15:21 UTC by bobo122b

added rate limiting to all routes

2023-07-08 13:49 UTC, Deadreyo requested changes
Just some small changes needed

2023-07-08 13:49 UTC, Deadreyo commented on src/middlewares/rate-limiter.ts
> +  max: 120,
The limit of 120 per 5 seconds is too big and doesn't help. Limit it to 20 requests per 60 seconds.

2023-07-08 13:49 UTC, Deadreyo commented on src/routers/auth.router.ts
> +authRouter.use(limiter);
You used the limiter on global router already, no need to have it here.

2023-07-08 13:49 UTC, Deadreyo commented on src/routers/participant.router.ts
> +  .use(limiter)
You used the limiter on global router already, no need to have it here

2023-07-08 13:49 UTC, Deadreyo commented on src/routers/participant.router.ts
> +  .post("/add", mwValidateParticipant, addParticipant)
The `/add` endpoint in participants need a dedicated limiter to limit it stricter than the others. Could be limited to 4 submissions per 2 hours for example.

2023-07-18 14:33 UTC, nightknighto approved these changes
Done the requested changes myself

2023-07-18 14:33 UTC, merged